### ISSUE TITLE
monthly report heading

### ISSUE THREAD

**Issue by Innocent-Anthony** [SoftmedTanzania/opensp-client-chw-vmmc#5]
The heading should resemble the [monthly report tool](https://docs.google.com/spreadsheets/d/1829LojFUdiJBDOYrr61x4y43wsBg6GOs/edit?usp=sharing&ouid=113011554164738573922&rtpof=true&sd=true)

**Comment by Innocent-Anthony** [comment]
rename vuluntary to voluntary

**Comment by tbwahacker** [comment]
ok

**Comment by tbwahacker** [comment]
done
