### ISSUE TITLE
WAJA -TRANSLATION

### ISSUE THREAD

**Issue by muyaso** [SoftmedTanzania/opensp-client-chw-vmmc#58]
- please translate the following

- [ ] reason for referral- Sababu ya rufaa
- [ ] voluntary medical male circumcision- Tohara kwa wanaume
- [ ] other reason-Sababu nyingine
- [ ] choose referral facility -Chagua kituo cha rufaa
- [ ] please select the appointment date-Tafadhali chagua tarehe ya miadi 
- [ ] save-HIFADHI

**Comment by Innocent-Anthony** [comment]
highlighted area should be translated to Fomu ya rufaa kwa ajili ya huduma ya tohara kwa wanaume
![Image](https://github.com/SoftmedTanzania/opensp-client-chw-vmmc/assets/112845415/5977aaac-6f77-48cd-b0f1-dfe55906df1b)


highlighted area should be rephrased to Huduma ya tohara kwa wanaume
![Image](https://github.com/SoftmedTanzania/opensp-client-chw-vmmc/assets/112845415/b6d84ed8-dd59-465a-b87c-f16c6787693b)
