### ISSUE TITLE
for indicator 6(moderate) some indicators duplicate in number

### ISSUE THREAD

**Issue by muyaso** [SoftmedTanzania/opensp-client-chw-vmmc#8]
- [ ] for indicator-Conversional method
- [ ] 1.excessive bleeding that requires pressure dressing to control,
- [ ] 2. excessive skin removed with tight skin but additional operative work not necessary 
- [ ] 3.  injury to the penis with bruising or abrasion of the glans or shaft of the penis.......
-the have double reflection
- [ ] username;nafubafac
- [ ] password:Nacp2022

**Comment by tbwahacker** [comment]
Got it, thanks!

**Comment by muyaso** [comment]
still the same
